version: '3'

services:
    app:
        image: node:18
        command: npm run dev
        ports:
            - '3000:3000'
        user: node
        volumes:
            - ./app:/app
        working_dir: /app
